### ISSUE TITLE
Tests claim to pass when they haven't

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/CI#80] opened 2016-09-22 15:06 UTC
See thaliproject/Thali_CordovaPlugin#956. The test output said:

Test 83268893919c9ad(919c9ad) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/83268893919c9ad_added_multiConnect__multiConnectResolved__multiConnectConnectionFailure_baydet/ for the logs

But if you click on the link and look at the iOS summary results you will see that they say false.

How can iOS be failing but the test says it passed? What's going on?

**Comment by larryonoff** [comment] 2016-09-22 15:24
@yaronyg It looks seems that it's already fixed in super-branch.

**Comment by larryonoff** [comment] 2016-09-22 15:36
I checked iOS code and it looks that iOS reports properly.

**Comment by yaronyg** [comment] 2016-09-22 18:19
Exactly but CI still reports a success even though iOS reported a failure! This is super bad.

**Comment by czyzm** [comment] 2016-09-23 04:29
For CI a failure means a ***_TEST_LOGGER:[PROCESS_ON_EXIT_FAILED]**_\* in logs. The issue is that the tests are failing but they report ***_TEST_LOGGER:[PROCESS_ON_EXIT_SUCCESS]**_*.

This is because there is a temporary code in UnitTest_app.js that is logging success and returning in order to omit the node tests. The bad result of native tests would be processed later.

For now, until we enable node tests we need to log the failure immediately.

**Closed as completed** 2016-09-23 04:47 UTC
Labels: bug
