### ISSUE TITLE
Make CI able to run smoke tests if we want

### ISSUE THREAD

**Issue by lesn1kk** [thaliproject/CI#79] opened 2016-09-22 11:55 UTC
We need to implement some logic when CI will enter test mode. Probably by adding additional field in mobile_test.json, then when someone will want to run smoke tests, he will have to enable it like:
"test": "true" or something.

**Comment by yaronyg** [comment] 2016-09-22 18:25
@mlesnic I removed the assignees because this isn't currently scheduled.

**Comment by yaronyg** [comment] 2016-09-26 20:43
This is implemented in thaliproject/Thali_CordovaPlugin#1030 and is a dupe of thaliproject/CI#74

**Closed as completed by yaronyg** 2016-09-26 20:43 UTC
