### ISSUE TITLE
WIFI connection to Accesspoint is unreliable with Android devices

### ISSUE THREAD

**Issue by DrJukka** [thaliproject/CI#7] opened 2015-10-30 10:12 UTC
Basing on the test results: https://raw.githubusercontent.com/ThaliTester/TestResults/48600797ce001f3_Story_001_juksilve_DrJukka/test_log.md

Each device sets Wifi & Bluetooth on successfully in the beginning. this can be verified by following log lines
"Turning radios to true
toggleBluetooth -
toggleWiFi"

Then from the logs it can be seen that following devices:
- samsung-SM-T232: (DEV6226)
- HUAWEI-ALE-L21: (DEV5429)

Are never assigned IP address other than local host, indicating that they are not having connection to the Access point, even when the Wifi has been successfully turned on.

As a second issue, from logs it can also be seen that some devices do lose the connectivity in the middle of the test. Following two devices are illustrating this:
- HTC-HTC Desire 820:(DEV3229)
- HTC-HTC One_M8: (DEV2969)

As it can be seen that they do have sonnectivity in the start, but then on some point middle of the run they start re-reporting connection error, and on that point they are only reporting to have the IP address for local host, indicating disconnection from the AP.

In general this test was better than average, most often the successful connections are well less than 20, and this time it was 22 out of 25 in beginning.

The missing device which did not make it to teh test was LGE-Nexus 5: (DEV2582), which for some reaso had really slow start and was connecting to the coordinator server late.

**Comment by obastemur** [comment] 2015-10-30 10:35
> Are never assigned IP address other than local host,

@DrJukka what do you mean ?

> As it can be seen that they do have sonnectivity in the start, but then on some point middle of the run they start re-reporting connection error, and on that point they are only reporting to have the IP address for local host, indicating disconnection from the AP.

Could you cherry pick the logs for the incidents and paste here ?

**Comment by DrJukka** [comment] 2015-10-30 11:03
I have simple code located in testUtils:
var networkInterfaces = os.networkInterfaces();
  Object.keys(networkInterfaces).forEach(function (interfaceName) {
    console.log("found interfaceName: " +interfaceName);
    networkInterfaces[interfaceName].forEach(function (iface) {
      console.log("-iface: " +iface.family + " is internal : " + iface.internal + ", has ip: " + iface.address);
    });
  });

And when there is no connection it only prints out:
"-iface: IPv4 is internal : true, has ip: 127.0.0.1"

Thus only network interface it finds is the local host, with successfull connections, you could see that when the server is not up yet, they are finding also interface which we have the server running at, for example the log line could be:
"iface: IPv4 is internal : false, has ip: 192.168.1.114"

**Comment by yaronyg** [comment] 2015-11-02 16:35
Please follow up on this with Oguz.

**Comment by vjrantal** [comment] 2015-11-03 10:18
I created a test PR that tries to turn on WiFi and do a simple HTTP request to bing.com. You can see the code delta I added (to a baseline that works in CI) at https://github.com/thaliproject/TestDummy/pull/44/files .

Currently, based on the logs, it passed on 6/25 devices. This pass estimation is based on searching keyword "PROCESS_ON_EXIT_SUCCESS" from https://github.com/ThaliTester/TestResults/blob/49526184791338a_Build_only_Android__vjrantal/test_log.md .

@obastemur: I assign this to you so that you could give your estimation on why the linked code doesn't pass the CI test in majority of the Android devices.

**Comment by vjrantal** [comment] 2015-11-03 17:29
@obastemur: I have now been able to do a couple of runs with a simple code change on top of your TestDummy codebase (https://github.com/thaliproject/TestDummy/pull/44/files). On every run, some amount of devices are not able to do an HTTP request. I wonder is there anything we could do to improve the situation?

**Comment by vjrantal** [comment] 2015-11-05 08:03
@obastemur: I now modified the test as we discussed yesterday (see commit message at https://github.com/thaliproject/TestDummy/commit/fb750166c2e7da885a9d26d17217dfa12f3b320c).

The first run indicated that 10/20 devices were able to do an HTTP request to the IP of jxcore.com. However, there was something in the logs that made me think there is something wrong in the CI currently. I'll contact you offline.

Good news was that I was able to see logcat output from 20/20 devices - great! :+1:

**Comment by vjrantal** [comment] 2015-11-05 10:40
Some more results from today:

3 tests that just toggle WiFi on (at the beginning of the test):
10/20, 11/20, 11/20

3 tests that first toggle WiFi off and then on (at the beginning of the test):
18/20, 17/20, 19/20

@DrJukka: I think this indicates that it would make sense to try turning WiFi off and then on if device can't connect, because clearly, it help bringing some devices back online.

@obastemur: There was one device that was never able to connect and it was called samsung-SM-T232.

Overall, I think we should do the following:
1. Make our tests to turn off -> on WiFi if connection unavailable and try again (as long as the test overall times out)
2. Monitor the percentage of devices that are able to connect and if it stays in numbers like we miss only 1 or 2, we could close this issue without further changes on the CI side
- We also need to monitor does a single device go into a state where it can't ever connect back without manual actions, because those we should consider replacing or eliminating from the device pool

**Comment by DrJukka** [comment] 2015-11-05 10:58
@vjrantal I have the code turning off and back on implemented in a way, that if we get connection error, after we have been getting connection. And this works sometimes, I have seen that when it fails I could go manually toggling the wifi in settings and it might do connect then again,

So it helps certainly, but its not solution.

**Comment by obastemur** [comment] 2015-11-06 14:16
I've been testing this on multiple devices and there is no way to reproduce this issue properly. Besides, keeping device awake also didn't help. Regardless from the device or CI, WiFi router this happens. Looking further on this issue.

**Comment by yaronyg** [comment] 2015-11-09 16:45
See #44

**Comment by yaronyg** [comment] 2015-11-10 15:38
No update today.

**Comment by yaronyg** [comment] 2015-11-11 15:36
No update today

**Comment by yaronyg** [comment] 2015-11-12 15:57
Oguz is going to work on this tonight.

**Comment by obastemur** [comment] 2015-11-12 16:39
Fixed. see https://github.com/thaliproject/Thali_CordovaPlugin/issues/314

**Closed as completed by obastemur** 2015-11-12 16:39 UTC
Labels: UX
